SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768

FPS = 60

# Animation duration
INITIAL_STATE_DURATION = 2.5
ANIMATION_DURATION = 0.5
FRAMES_INITIAL_STATE = int(FPS * INITIAL_STATE_DURATION)
FRAMES_ANIMATION = int(FPS * ANIMATION_DURATION)

# Make dimensions relative to screen size
ANIM_Y_HIGHEST_POS = int((150 / 480) * SCREEN_HEIGHT)  # Last position when the disk is removed from the peg in the
# animation

# Base (Pegs)
DISTANCE_BETWEEN_PEGS = int((193 / 640) * SCREEN_WIDTH)
SPACE_DISK_HEIGHT = int((4 / 480) * SCREEN_HEIGHT)
MAX_TOWER_HEIGHT = int((170 / 480) * SCREEN_HEIGHT)
BASE_LEFT = int((30 / 640) * SCREEN_WIDTH)
BASE_TOP = int((425 / 480) * SCREEN_HEIGHT)
PEGS_WIDTH = int((15 / 480) * SCREEN_HEIGHT)
PEGS_HEIGHT = int((187 / 480) * SCREEN_HEIGHT)
PEGS_TOP = int(BASE_TOP - PEGS_HEIGHT + 1)
PEG_CENTER_CENTER = int(SCREEN_WIDTH / 2)
PEG_LEFT_CENTER = int(PEG_CENTER_CENTER - DISTANCE_BETWEEN_PEGS)
PEG_RIGHT_CENTER = int(PEG_CENTER_CENTER + DISTANCE_BETWEEN_PEGS)

# Disks
MAX_DISK_WIDTH = int(0.95*DISTANCE_BETWEEN_PEGS)
MIN_DISK_WIDTH = int(0.2*DISTANCE_BETWEEN_PEGS)
MIN_DISK_HEIGHT = int((5 / 480) * SCREEN_HEIGHT)
MAX_DISK_HEIGHT = int((18 / 480) * SCREEN_HEIGHT)
